### ISSUE TITLE
Components are not being displayed when their status is "In Progress"

### ISSUE THREAD

**Issue by bladernr** [canonical-web-and-design/certification.ubuntu.com#104]
When one looks at vendor components on a cert on the public cert pages, e.g.:
https://certification.ubuntu.com/hardware/202005-27924

at the bottom is a list of Vendor Approved Options for that machine.  The Legend for the table clearly indicates one should see all components that have been marked as Certified, Unsupported, or In Progress.

However, for that entry, a user should see 10 "In Progress" entries and 1 "Certified" entry, but only the Certified entry is visible.

**Comment by codersquid** [comment]
This is actually a backend issue. I thought not showing non-certified components was the intent. I can fix that. I've opened a bug in the backend.
