### ISSUE TITLE
Release headings in the components table are hardcoded

### ISSUE THREAD

**Issue by codersquid** [canonical-web-and-design/certification.ubuntu.com#106]
While working on the api response for components, I checked how the table is constructed here and discovered that the releases in the table header are hardcoded.

https://github.com/canonical-web-and-design/certification.ubuntu.com/blob/master/templates/components/index.html#L52

This needs to be changed to list the releases in the header dynamically based on the currently supported LTS releases.

You need to add an extra api call to the releases endpoint to create a list of supported releases to pass as a context variable to the template so that you can iterate over it when rendering the table headings and then again when populating the table. On the private version of the site we do something similar though it's not pretty.

I'll see if I can help with a MR.

**Comment by nottrobin** [comment]
Thanks @codersquid, that would be very helpful.

Does this mean that that page is not showing 20.04 when it should be?

**Comment by codersquid** [comment]
> Does this mean that that page is not showing 20.04 when it should be?

That's correct. It also means that anytime LTS releases get added or dropped that the table would need to be changed by  hand. I have an api proposal that would add an endpoint to return a list of LTS releases to get used here. Once that's in I can help with this.

**Comment by nottrobin** [comment]
@codersquid if this is a live issue now, shouldn't we go and manually update the HTML ASAP while we wait for the proper fix?

**Comment by codersquid** [comment]
> @codersquid if this is a live issue now, shouldn't we go and manually update the HTML ASAP while we wait for the proper fix?

I've made a branch that does that, but the /components page table overhangs the page. I'm not sure how to fix that. Is it more important to have the headings than not?

![tableoverhang](https://user-images.githubusercontent.com/529748/89666288-b49fe980-d89f-11ea-8d38-be6c50e65285.png)
