### ISSUE TITLE
Translate the pages strings 

### ISSUE THREAD

**Issue by b-m-f** [canonical-web-and-design/certification.ubuntu.com#11]
Translate all the strings on the website.

https://launchpad.net/hexr contains them in `public/locale`

**Comment by nottrobin** [comment]
Is this something that exists on the current site?

**Comment by b-m-f** [comment]
Yup, apparently so :)

**Comment by nottrobin** [comment]
As far as I can see, the existing certification.ubuntu.com site hardly has any actual translations - viewing the site in German shows entirely English text.

In general, I don't think crowd-sourced or manual translation of site strings is ever very effective for websites - they will always be very patchy at best. Users simply using e.g. Google Translate to translate the site are likely to have a *much* better experience.

As discussed with @b-m-f, I'm going to close this for now.
