### ISSUE TITLE
Component tables are not showing release indicators

### ISSUE THREAD

**Issue by codersquid** [canonical-web-and-design/certification.ubuntu.com#137]
I don't know when this started happening, but I've noticed that the release cells in the components tables no longer show a checkmark or ? for component entries The backend hasn't changed.

When I look at the template I see that it puts a checkmark if a string matches against the value in the api response, which seems like it should be showing checkmarks. I'm not sure what is going on.

(Note: The template logic is wrong because it does not check the status type. The logic there means that it will put a checkmark regardless of status)

**Comment by SirSamTumless** [comment]
@nottrobin Could you look into this and triage it accordingly?

**Comment by codersquid** [comment]
Oh, the api started returning release information in `lts_releases` instead of `lts_certified_releases` and I didn't inform you. I probably intended to make the change for you and forgot.

**Comment by codersquid** [comment]
I made a PR with the change so that it shows checkmarks again.

I didn't make a change to have it show the appropriate mark for when the status is inprogress, I'm not certain how to do {% with status = foo["blah"].status %} to be able to use status as a variable for checking conditionals so that the template isn't as wordy as how it checks for third party.

**Comment by nottrobin** [comment]
Thanks @codersquid this was really helpful.
