### ISSUE TITLE
components do not show ? for In Progress statuses

### ISSUE THREAD

**Issue by codersquid** [canonical-web-and-design/certification.ubuntu.com#141]
When a component release status is inprogress a ? should be shown instead of a checkmark.

Here's an example call that returns statuses that are in progress. https://certification.canonical.com/api/v1/componentsummaries/?format=json&canonical_id=202005-27924

I think the logic should show a checkmark or a ? and leave the status blank for ones that are unsupported. an entire array of x's would look pretty ugly.

**Comment by carkod** [comment]
I think @bethcollins92 already addressed this?

**Comment by bethcollins92** [comment]
Yeah, this has been addressed see below. [PR](https://github.com/canonical-web-and-design/ubuntu.com/pull/9537) here

![image](https://user-images.githubusercontent.com/58959073/115712415-a41b9a80-a36c-11eb-914a-05f83900295a.png)
