### ISSUE TITLE
[Model pages] Visual design

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/certification.ubuntu.com#153]

**Comment by anasereijo** [comment]
Visual design: https://zpl.io/VO4yeN1
UX: https://docs.google.com/document/d/1vIf1vC1mg72JbzmahrcKCaRZN-qMLCgin_i9iqjUxpM/edit#heading=h.1qr5knyqfc4w

**Comment by anasereijo** [comment]
closing, as @spencerbygraves +1'd this
