### ISSUE TITLE
[Model pages] Build 

### ISSUE THREAD

**Issue by SirSamTumless** [canonical-web-and-design/certification.ubuntu.com#154]

**Comment by anasereijo** [comment]
@bethcollins92 this is ready for you 

Visual design: https://zpl.io/VO4yeN1
UX: https://docs.google.com/document/d/1vIf1vC1mg72JbzmahrcKCaRZN-qMLCgin_i9iqjUxpM/edit#heading=h.1qr5knyqfc4w

**Comment by anasereijo** [comment]
please estimate
