### ISSUE TITLE
Search results filter list too long

### ISSUE THREAD

**Issue by bethcollins92** [canonical-web-and-design/certification.ubuntu.com#176]
The update button isn't obvious enough as the list of vendors/filters in general is too long. The form-factor pages should also display different headings than the search results page, but when filters are applied the heading should revert to the search results page.

**Comment by codersquid** [comment]
One thing to consider with this is that a user who wants to search multiple options, for example Lenovo Desktops and Laptops, will have two extra searches -- check Desktop, check Laptop, check Lenovo. Whereas with the button it's just one search.
