### ISSUE TITLE
Update navigation.yaml to work with queries

### ISSUE THREAD

**Issue by bethcollins92** [canonical-web-and-design/certification.ubuntu.com#178]
On /certification, the secondary nav doesn't have the correct active state as the paths contain queries.

**Comment by anthonydillon** [comment]
This one is set to Icebox and this milestone.

**Comment by bethcollins92** [comment]
@anthonydillon fixed, thanks!

**Comment by carkod** [comment]
No longer relevant as we are [removing these pages](https://docs.google.com/document/d/1FRi83535YcpAv3jJ2lb4dpcBNlviA2JomD0d9gD5yAQ/edit)

**Comment by carkod** [comment]
Not carrying on with this. Check (PR)[https://github.com/canonical-web-and-design/ubuntu.com/pull/9774] conversation
