### ISSUE TITLE
reduce the number of API calls in the model details view

### ISSUE THREAD

**Issue by codersquid** [canonical-web-and-design/certification.ubuntu.com#180]
The model details view is making a call to `api.certified_models` in addition to `api.certified_model_details`. I've updated the API for certified_model_details to include `category` and `make`.

I can update the view once the WIP is done, if needed, unless someone gets to it first. It's not a lot of work.

Here is a quick summary of how the certified_models response is being used and how the certified_model_details response should be used instead.

* For `get_download_url` (note, the new design wireframes don't have download so this could be removed entirely)
* For `model_names`: use `model` in the details response.
* For `category`: use `category` in the details response
* For `vendor` in the call to `render_template`: use `make` in the details response
* For `major_release` in the call to `render_template`: use `certified_release` in the details response.

**Comment by carkod** [comment]
@codersquid Thanks for improving this. I think nobody is going to get to it now, I will not be tackling this anytime soon, so you can do it you want. 

Regarding `get_download_url` function, I believe beth is using it now [here](https://github.com/canonical-web-and-design/ubuntu.com/pull/9551/commits/e7adf54351115362234a662d585106ec2295bfae)?
