### ISSUE TITLE
Improve UX on vendor specific search results page

### ISSUE THREAD

**Issue by bethcollins92** [canonical-web-and-design/certification.ubuntu.com#183]
Looking at the wireframe, the vendor pages were supposed to have a logo and some introductory text, making it clear to the user they are on a vendor specific search page. However, this is not something we are able to display as we don't have this data, so now the page looks very similar to the generic search results page and could be confusing to the user. UX help is needed on this.

**Comment by cassiocassio** [comment]
- logos and text were part of a plan to engage our best vendors / partners with a bit of love, starting with a logo for the top handful

- sourcing the top 5 logos would probably cover 80% of the server market

- if the db cant' to that then so be it

2nd point, but probably more important is the UX of feeling 'trapped' once you navigate to a Vendor page

A discussion an some options here:

https://zpl.io/2p3v1Oy

@elioqoshi @wgx :eyes: Certification escapology

**Comment by elioqoshi** [comment]
Sorry I am unable to digest the information here. Could you provide a little more context? Looking at Zeplin I am not sure what the ask is here.

Regarding Beth's original point, can't we source the logos and some introductionary content ourselves?

Providing some meta info for vendors on top of the page would likely help to differentiate the pages from the generic search page.

**Comment by wgx** [comment]
A quick patch would be a pre-checked checkbox:

- [x] Dell

Which a user can un-check to 'escape' from Dell-land. 

![image](https://user-images.githubusercontent.com/930099/116044748-32439980-a669-11eb-89c4-01ea13ed5043.png)

>and some introductionary content ourselves?

Yeah.. even some generic intro from Wikipedia would be fine to orient users:

> Dell is an American multinational computer technology company that develops, sells, repairs, and supports computers and related products and services. Founded in 1984 by Michael Dell, the company is one of the largest technology corporations in the world, employing more than 165,000 people in the U.S. and around the world.

**Comment by elioqoshi** [comment]
> Yeah.. even some generic intro from Wikipedia would be fine to orient users:

I was thinking similarly. Basically what google search does.

**Comment by bethcollins92** [comment]
Thanks for the input @elioqoshi @wgx and @cassiocassio. I'm working on a solution now, the issue we have is all the data on the page is sent from a database that we (the web squad) don't have access to/maintain. I can ask if it's possible to add intro text/logo to the database, but there are a total of 34 vendors so it is quite a big ask. 

Could a possible solution be (if we are able to add to the db) to add a logo and intro text to say 5 of the biggest/most important vendors only? Or would this cause problems with the companies who we don't do this for?

**Comment by wgx** [comment]
>Could a possible solution be (if we are able to add to the db) to add a logo and intro text to say 5 of the biggest/most important vendors only? 

Totally fine. As @cassiocassio says - once you've added Dell, Lenovo, and a few others, that's 80% of the market...

**Comment by codersquid** [comment]
There's actually thousands of vendors in the database since the data comes from scraping vendor strings from udev information or pci.ids or usb.ids. That API gets vendors from that information, not from information that is hand-curated, so it doesn't make sense to add this as a feature to the API.

**Comment by bethcollins92** [comment]
Waiting on copy
