### ISSUE TITLE
Vendor pages showing an array in the title

### ISSUE THREAD

**Issue by carkod** [canonical-web-and-design/certification.ubuntu.com#186]
## Summary
Click any vendor in the results page column e.g. /certification?vendor=Dell&vendor_page=True

![vendor-page-issue](https://user-images.githubusercontent.com/14939793/116396985-ec7c0200-a81d-11eb-956a-a4820c2d1f7b.png)

**Comment by bethcollins92** [comment]
This is fixed [here](https://github.com/canonical-web-and-design/ubuntu.com/pull/9646/files)
