### ISSUE TITLE
Hardware Summary and Hardware Details are conflated between certificates

### ISSUE THREAD

**Issue by bladernr** [canonical-web-and-design/certification.ubuntu.com#32]
https://certification.ubuntu.com/hardware/201605-22234/

On that entry, there are three certificates (14.04, 16.04 and 18.04). The hardware in Hardware Summary, and Hardware Details, is an aggregation of the hardware details from all three.  This is incorrect and confusing as it is quite possible that the 

Broadcom Corporation NetXtreme II BCM57810 10 Gigabit Ethernet

For example, did not even exist in 2014 and was never supported on 14.04. As an external user, this could be confusing as it implies that this 10Gb device is certified for 14.04.

(note, the above is only used as an exampleb what-if, for this case, the chipset WAS supported by 14.04, but that may not always be the case).

as a suggestion that could resolve this:

1: Remove the "Hardware Summary" and "Hardware Details" lists
2: For each certificate, add a "Hardware Details" clickthrough link
3: The Hardware Details clickthrough takes the users to the Hardware Details for $MACHINE for THAT CERTIFICATE ONLY and does not conflate/aggregate the hardware details from other certified releases.

This would preserve hardware details while also preventing situations where a machine is tested on 14.04 prior to 100Gb NICs being a thing, and also is tested on 18.04 WITH a 100Gb NIC, and having that 100Gb NIC being listed in a way that could imply it is also supported by 14.04.

**Comment by matthewpaulthomas** [comment]
I’ve now mostly adopted this proposal in [my design for the model page](https://docs.google.com/document/d/1vIf1vC1mg72JbzmahrcKCaRZN-qMLCgin_i9iqjUxpM/edit#heading=h.1qr5knyqfc4w): each release will have its own hardware summary (processor, network, video), but will then link to a “Hardware details” page per release.
