### ISSUE TITLE
Hide "Certification Notes" when there are no notes to display.

### ISSUE THREAD

**Issue by bladernr** [canonical-web-and-design/certification.ubuntu.com#33]
Every certificate includes a "Certification Notes" statement that says by default "There are no notes for this release."

It would be cleaner, and make more sense, to hide the "Certification Notes" section rather than displaying it only to say there are none.

**Comment by nottrobin** [comment]
Thanks @bladernr. Marking this to be done as part of the redesign work.

**Comment by matthewpaulthomas** [comment]
This seems to have been fixed:
- [The ThinkSystem SR590 page](https://certification.ubuntu.com/hardware/201711-25983) has non-empty “Certification notes” for Ubuntu 16.04 LTS, and no equivalent heading for 18.04 LTS or 20.04 LTS.
- [The Huawei 2288C V5, 2288H V5 page](https://certification.ubuntu.com/hardware/201707-25596) has non-empty “Certification notes” for three of the seven release×kernel combinations listed, and no heading for the others.
- [Google has only one record of any certification.ubuntu.com page using the phrase “There are no notes for this release.”](https://www.google.com/search?q=%22There+are+no+notes+for+this+release.%22+site%3Acertification.ubuntu.com), and [the page itself](https://certification.ubuntu.com/hardware/201703-25446) no longer does.
