### ISSUE TITLE
Redesign of Machine Page

### ISSUE THREAD

**Issue by bladernr** [canonical-web-and-design/certification.ubuntu.com#49]
https://certification.ubuntu.com/hardware/201706-25574/

There are several issues here to sort through, so it's possible this needs to be broken into separate bugs but for now, I'd suggest the following changes to the machine details page on the public site:

1:  Expand "Hardware Summary" to contain the major component groups (e.g. Processor, Video, Network, RAID, GPU/Video, GPGPU, etc)

2:  Remove "Hardware Details" because all the "important" details would now live in "Hardware Summary" and because the "Details" list is often way too noisy with things of little value on the public site, such as: BIOS (because the BIOS tested is usually different than what a customer buys, Other, because this is almost always full of many (sometimes >100) lines of data like "Intel Sky Lake-E FOO Registers" that is simply a baked in piece of the motherboard or CPU, not something anyone can do anything about, nor make purchasing decision based on.

3: Split Hardware Summary based on the certificate, and move Hardware Summary into the Certificate box itself.  Historically, this design has conflated the hardware on machines tested.  Using the example above, if you look at  RAID, it would appear that both RAID devices are certified on both 16.04 and 18.04. However, in reality, the SAS-3 3108 controller was certified for 16.04 on this machine, NOT 18.04, which was done using a different RAID card.

As another scenario, it's possible that a Model is refreshed from Skylake to Cascade Lake, and the Skylake one was certified on 16.04 w/ 4.4, while Cascade Lake was certified on 18.04 with 4.15.  Current design would make it seem that Cascade Lake is also certified for Xenial GA, which it is not, because CLX support only begins at 4.15 and later.  So splitting these summaries apart would help ease that confusion.

4: If the above are implemented, the Vendor Approved Options table would move much higher on the page, and would then become easier to find.  As it is today, on the example above, it is buried underneath all the noise of "Hardware Summary" and it's very likely will not be seen unless someone scrolls all the way to the bottom of the page.  (An alternate solution here would be to move this table up between the current Certificate boxes and the Hardware Summary section, however, I think disaggregating the summary and removing "Details" would do a better job of cleaning this up.

One final alternate suggestion would be:
Place a "Hardware Details" link on each certificate box that would open a page with the "Hardware Summary" and "Hardware Details" for that certified version (so on this example, the 16.04 would open a page using the hardware details from the 16.04 submission, and the 18.04 link would open a page using the hardware details from the 18.04 submission). thus removing that from the main machine page alltogether.
This would clean this page up to only the Certificate blocks and the Component table while preserving the gory details should someone wish to see them.

**Comment by matthewpaulthomas** [comment]
> 1: Expand "Hardware Summary"…
> 2: Remove "Hardware Details"

This is covered by #51. 

> the "Details" list is often way too noisy with things of little value on the public site

This is covered by #52.

> 3: Split Hardware Summary based on the certificate, and move Hardware Summary into the Certificate box itself.

This is covered by #32.

> 4: If the above are implemented, the Vendor Approved Options table would move much higher on the page

Currently, Google finds [only one machine page with “Vendor Approved Options”](https://certification.ubuntu.com/hardware/201711-25983), it’s not a table, and it’s above both the Hardware Summary and the Hardware Details. So I guess this issue has been fixed.

> Place a "Hardware Details" link on each certificate box that would open a page with the "Hardware Summary" and "Hardware Details" for that certified version

This is covered by #32.

**Comment by bladernr** [comment]
> Currently, Google finds only one machine page with “Vendor Approved Options”, it’s not a table, and it’s above both the Hardware Summary and the Hardware Details. So I guess this issue has been fixed.

Negative... Apologies for the confusion.  We refer to them as "Vendor Approved Options" in all the contracts and such, on the page, there's a table called "Component Devices" and that is what I meant.  Your search revealed a note, which isn't what I was talking about.

[Google shows 10 ](https://www.google.com/search?q=%22Component+Devices%22+site%3Acertification.ubuntu.com&oq=%22Component+Devices%22+site%3Acertification.ubuntu.com&aqs=chrome..69i57.9800j0j7&sourceid=chrome&ie=UTF-8 )(plus some other non-machine-specific pages) that have a 
Component Devices table, that appears at the very bottom of each entry.

It's THAT table that should come closer to the top.

This needs some further discussion from a design perspective, but i wonder if it wouldn't be better to have the certificate date on top with a button for "Machine Details", and then the component devices table next.  And clicking on the "Machine Details" button would open a page with all the data currently in the Summary and Details lists. *Note, this bit, at least, is covered as you suggest by #32

**Comment by matthewpaulthomas** [comment]
> Google shows 10 (plus some other non-machine-specific pages) that have a Component Devices table, that appears at the very bottom of each entry. It's THAT table that should come closer to the top.

Thanks for the clarification. In [the new design](https://docs.google.com/document/d/1vIf1vC1mg72JbzmahrcKCaRZN-qMLCgin_i9iqjUxpM/edit#heading=h.1qr5knyqfc4w), this section is called “Components certified with this system” and it’s still at the bottom of the page. Placing it higher would mean putting it above the certification details, which I don’t think you were suggesting. I guess it will be higher on the page in an absolute sense, since the hardware details that were above it are now relegated to separate pages.
