### ISSUE TITLE
Server SoC and Server type systems appearing under "Desktop" 

### ISSUE THREAD

**Issue by bladernr** [canonical-web-and-design/certification.ubuntu.com#68]
Looking at a random selection of server cert pages, e.g.

https://certification.ubuntu.com/hardware/201909-27367
https://certification.ubuntu.com/hardware/201812-26699
https://certification.ubuntu.com/hardware/201606-22453

...they appear to show a desktop search path "Ubuntu Desktop ›Search Results ›Detail" (text above the cert title).

I would have expected this to reflect a "server" search path (e.g. "Ubuntu Server ›Search Results ›Detail"), or be agnostic (e.g. "Ubuntu Server ›Search Results ›Detail")

**Comment by bladernr** [comment]
Note, if you go here: https://certification.ubuntu.com/server/models?vendors=QUANTA%20Computer%20Inc

The breadcrumbs say: "Ubuntu Server ›Search Results"

But as soon as you click on a system for more detail: https://certification.ubuntu.com/hardware/201410-15838

The breadcrumbs change to this: Ubuntu Desktop ›Search Results ›Detail

**Comment by codersquid** [comment]
The API identifies these as Server SoC and Servers, respectively.

https://certification.canonical.com/api/v1/certifiedmodels/?format=json&canonical_id=201909-27367
https://certification.canonical.com/api/v1/certifiedmodels/?format=json&canonical_id=201812-26699
https://certification.canonical.com/api/v1/certifiedmodels/?format=json&canonical_id=201606-22453
