### ISSUE TITLE
Please add coverage guides to public website

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-web-and-design/certification.ubuntu.com#71]
Please add guides like [this](http://certification-static.canonical.com/docs/coverage_by_release/18.04/DesktopCoverage1804.pdf) to the public c.u.c site.

**Comment by matthewpaulthomas** [comment]
For my own reference in designing this: these documents are indexed in
- [ ] [certification-static.canonical.com/docs](http://certification-static.canonical.com/docs/)
- ~~[certification-static.canonical.com/checkbox-ihv](http://certification-static.canonical.com/checkbox-ihv/)~~ — eight years out of date
