### ISSUE TITLE
Certification kernel could be more clear

### ISSUE THREAD

**Issue by bladernr** [canonical-web-and-design/certification.ubuntu.com#79]
https://certification.ubuntu.com/hardware/201807-26311

Looking at that page, we see text like this for each release certified:

> Testing details
> This system was tested with 18.04 LTS, running the 4.15.0-46-generic kernel.
> 
> Certification notes
> There are no notes for this release.

Some of our partners are complaining that their customers (and the partners themselves, in some cases) get confused because we list the release and the exact kernel tested, but don't convey that the certificate is good for that kernel and every relevant kernel afterwards.

For example, in the above text, that implies that it was certified for 18.04 using the GA 4.15 kernel and is also considered certified for every point release and HWE kernel that follows.  But we're not terribly clear on that.

For the Testing Details section, we should clarify exactly what we mean with some sort of different or additional text, for example:, change "Testing details" to "Certification details" like so:

Certification details
This system has been certified for 18.04 LTS using the 4.15.0-46 kernel and is considered certified for all 18.04 LTS point releases and HWE kernels as well.

As for the "Certification notes" section, rather than the majority of these blocks having a "No notes here" message, the "Certification notes" bit should only appear when there are actually notes.

**Comment by bladernr** [comment]
Why was this closed... will it be addressed in the current redesign?  It is still something I hear about periodically from vendors because we are not clear that a system that is certified with kernel X.Y is also considered certified for all following SRU and HWE kernels and LTS point releases for that particular LTS family.

**Comment by SirSamTumless** [comment]
We are cleaning up old issues so we can start the move of certs to u.c. It also looks like a PR was closed with this issue if you look through the history?
