### ISSUE TITLE
Column ordering is off

### ISSUE THREAD

**Issue by bladernr** [canonical-web-and-design/certification.ubuntu.com#96]
Looking at the server landing page: https://certification.ubuntu.com/server

The columns are now out of order with 20.04 coming after the 14.04 column.  The columns should read from Left to Right with 20.04 being the left most at this point.

**Comment by codersquid** [comment]
The app populates releases based on https://certification.canonical.com/api/v1/certifiedreleases/?format=json and that is returning things in the order you'd expect.

**Comment by codersquid** [comment]
I'm wrong, that is how the desktops page works. The server page uses a different api. Server is special. 
https://github.com/canonical-web-and-design/certification.ubuntu.com/blob/master/webapp/app.py#L227

**Comment by codersquid** [comment]
Here's an example response.

```
{
  "14.04 LTS": 64,
  "16.04 LTS": 48,
  "18.04 LTS": 46,
  "20.04 LTS": 1,
  "releases": [
    "20.04 LTS",
    "18.04 LTS",
    "16.04 LTS",
    "14.04 LTS"
  ],
  "total": 159,
  "vendor": "Dell EMC"
},
```

**Comment by bladernr** [comment]
OK, so the way that was supposed to work is:

Order columns by release (Newest to Oldest)
Order Vendor Rows by number of certs in the most recent column...

Personally, I wonder if ordering vendors alphabetically wouldn't be more neutral, but ISTR I was overrulled by sales people the last time I suggested that.
