### ISSUE TITLE
 Link for sof-skl_hda_card HDMI/DP, pcm=11 Jack tells "no results found" although present in some systems

### ISSUE THREAD

**Issue by mhampl** [canonical-web-and-design/certification.ubuntu.com#97]
https://certification.ubuntu.com/hardware/201906-27090 shows several items in the "Other" category.

KIOXIA Corporation sof-skl_hda_card HDMI/DP, pcm=11 Jack links to the page
https://certification.ubuntu.com/catalog/component/input:sof-skl_hda_cardHDMI---DP,pcm=11Jack
and there is says "No results found."

**Comment by matthewpaulthomas** [comment]
[That Dell Vostro page](https://certification.ubuntu.com/hardware/201906-27090) no longer mentions any KIOXIA component.

**Comment by mhampl** [comment]
The web page https://certification.ubuntu.com/hardware/201906-27090 now does not show KIOXIA any more, but it lists items like
Union Memory (Shenzhen) sof-skl_hda_card HDMI/DP, pcm=11 Jack
If you follow the link from that entry to
https://certification.ubuntu.com/catalog/component/input:sof-skl_hda_cardHDMI---DP,pcm=11Jack
you see "No results found." which is exactly the same problem as originally reported.
